### ISSUE TITLE
Unable to access uploaded files

### ISSUE THREAD

**Issue by drzackyll** [unicef/sir-releases#170]
See screenshots. When file link is clicked, I get and error. Perhaps there is a problem with the URL.

**Comment by drzackyll** [comment]
<img width="1025" alt="screen shot 2018-10-11 at 3 34 01 pm" src="https://user-images.githubusercontent.com/8411545/46829268-4e151780-cd6b-11e8-8e4e-51fc4f45f310.png">
<img width="980" alt="screen shot 2018-10-11 at 3 33 54 pm" src="https://user-images.githubusercontent.com/8411545/46829269-4e151780-cd6b-11e8-9127-8bcb1751cdb9.png">

**Comment by daniel-tabarcea** [comment]
@reinbach is the url for the file the correct one?

**Comment by reinbach** [comment]
Just pushed a tweak to backend URLs that should fix this issue

**Comment by drzackyll** [comment]
@reinbach still having some trouble with this. here's a screenshot that shows the url i'm getting in the front end
![Screen Shot 2018-10-17 at 2.11.14 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f46b7191a37af1132a4f5e5b5ecc3c4a4356bcbbd671f3e57862804e0ebfd96b097dc23510a9bd8316b601ba21d94782b6e88c18d2f42f67b6d5db1063474f4dcbed5727a19e41c95df542e6445cad113460e3722431.png)

**Comment by drzackyll** [comment]
if i manually make that `localhost:8080`, i get `ENOENT: no such file or directory, stat '/code/media/incident/attachment/Screen_Shot_2018-10-16_at_3.01.25_PM.png'`

**Comment by reinbach** [comment]
@drzackyll are you running this locally? what is the url for the backend?

**Comment by drzackyll** [comment]
@reinbach yes running locally. on the demo version deployed now, here is the result: 
<img width="1209" alt="screen shot 2018-10-17 at 3 36 59 pm" src="https://user-images.githubusercontent.com/8411545/47111883-c4f65880-d222-11e8-92b5-8cea783349fb.png">

**Comment by adi130987** [comment]
@reinbach what's the status on this issue?

**Comment by reinbach** [comment]
@adi130987 this has been resolved I believe

**Comment by adi130987** [comment]
@reinbach does it work on local environment? (it doesn't work on my env)

**Comment by reinbach** [comment]
@adi130987 I know we got it working on demo site, I'll take a look and see what the issue is locally

**Comment by drzackyll** [comment]
I'm now getting an authentication error when I try to upload on local and demo
![Screen Shot 2018-10-29 at 12.07.21 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b8008c1b0c3c0012343c85/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456fa6b7191a379ed0c2b56415d4fbc21254d58eeb9cb74fce36f34985619e883655922cf3919adbd871eb608ba208a1d8db1bcde4a94fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34fe14556ad15346be474366e0a.png)
<img width="1267" alt="screen shot 2018-10-29 at 3 08 46 pm" src="https://user-images.githubusercontent.com/8411545/47673980-936b7e80-db8c-11e8-8300-5d6bf57d2e2f.png">

**Comment by drzackyll** [comment]
connects to #274

**Comment by reinbach** [comment]
Links to attachments should be working locally now. May need to rebuild backend and proxy containers locally
